"""Write docs/schemes.js from data/schemes.yaml so the web page and the API share one
source of truth. Run after editing the YAML:  python scripts/export_web_data.py"""

import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
schemes = yaml.safe_load((ROOT / "data" / "schemes.yaml").read_text(encoding="utf-8"))["schemes"]
body = json.dumps(schemes, ensure_ascii=False, indent=1)
(ROOT / "docs" / "schemes.js").write_text(
    "/* Generated by scripts/export_web_data.py from data/schemes.yaml. Do not edit. */\n"
    "(function (root) {\n  var S = " + body + ";\n"
    "  if (typeof module !== 'undefined' && module.exports) module.exports = S;\n"
    "  else root.URIMAI_SCHEMES = S;\n"
    "})(typeof window !== 'undefined' ? window : globalThis);\n",
    encoding="utf-8",
)
print(f"wrote docs/schemes.js with {len(schemes)} schemes")
